### ISSUE TITLE
userscript  for http://wiki.microfocus.net/

### ISSUE THREAD

**Issue by okurz** [aspiers/desktop-config#4]
Your user scripts are an awesome help for auto-login on some pages with annoying and slow behaviour, thank you very much!
It would be great if you could provide a userscript for http://wiki.microfocus.net/ as well or give me a little hint how I could accomplish that myself.

**Comment by okurz** [comment]
solved by https://github.com/aspiers/desktop-config/pull/5

**Comment by okurz** [comment]
learned some javascript by this :-)

**Comment by aspiers** [comment]
Awesome! thanks :-) be sure to check out the other userscripts if you didn't already!

**Comment by okurz** [comment]
yes, I did. thank you. I am not quite sure yet how to use them though but I will experiment :-)

The login scripts at least mitigate the problem with annoyingly long login times.

**Comment by aspiers** [comment]
Well there's a [README](https://github.com/aspiers/desktop-config/blob/master/lib/browser/userscripts/page-id-helpers/README.md) at least ;-)
